apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-frontend-deployment
spec:
  selector:
    matchLabels:
      app: test-frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: test-frontend
    spec:
      containers:
      - name: test-frontend
        image: test-frontend
        ports:
        - containerPort: 80

