apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-frontend-deployment
spec:
  template:
    spec:
      containers:
      - name: test-frontend
        imagePullSecrets:
        - name: github-package-cred

